name: GitHub Pages hosted website
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: retypeapp/action-build@next
        with:
          config_path: en/
          key: ${{ secrets.RETYPE_KEY }}

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true